/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg124guirevision;

import java.awt.CheckboxGroup;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Locale;
import static java.util.concurrent.ThreadLocalRandom.current;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author renziverdb - git 
 */
public class AddDentalRecord extends javax.swing.JFrame {

    /**
     * Creates new form AddPatient
     */
    Connection con;
   //PatientRecords pr = new PatientRecords();
  // int  patId =pr.getPatientID();
   //String patlName=pr.getPatientlName();
   //String patfName=pr.getPatientfName();
    public AddDentalRecord() {
        
        initComponents();
        
        
          try{
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            String url = "jdbc:derby://localhost:1527/Dental Clinic";
            String user = "maximus";
            String pass = "maximus123";
            con = DriverManager.getConnection(url, user, pass);
        }
        catch(Exception e){
           System.out.println(e);
        }
    }
    static int patId;
    static String ln;
    static String fn;
    static String mi;
    static String contact;
    static JFrame gui;
    
    public AddDentalRecord(int patId, String ln, String fn)
    {
        this.patId = patId;
        this.ln = ln;
        this.fn = fn;
       
    }
    
    
      private void AddData( String dentalToothNum, Date DentalDate, String dentalDescription, Double totalAmount, 
              Double amountPaid, Double balance, String addDentalDate, String addDentalEvent)
    {
        try
        {
             
            String qry = "INSERT INTO DENTAL_RECORD( PATIENT_ID , TOOTH_NO, PATIENT_DATE, DESCRIPTION, TOTAL_AMOUNT, AMOUNT_PAID,BALANCE,TIME_STAMP) VALUES((SELECT PATIENT_ID FROM PATIENT_RECORD WHERE PATIENT_RECORD.PATIENT_ID = ?),?, ?, ?, ?, ?,?,?)";
            
            PreparedStatement pstmt = con.prepareStatement(qry);
            pstmt.setInt(1, patId);
            pstmt.setString(2,dentalToothNum);
            pstmt.setDate(3, DentalDate);
            pstmt.setString(4, dentalDescription);
            pstmt.setDouble(5, totalAmount);
            pstmt.setDouble(6, amountPaid);
            pstmt.setDouble(7, balance);
            pstmt.setString(8,addDentalDate);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "The data has successfully added!");
            
            
            String qry2 = "INSERT INTO HISTORY(DATE, EVENT) VALUES(?,?)";
            
            PreparedStatement pstmt2 = con.prepareStatement(qry2);
            pstmt2.setString(1, addDentalDate);
            pstmt2.setString(2,addDentalEvent);
            pstmt2.executeUpdate();
            
            
            new DentalRecords().setVisible(true);
            super.dispose();
            
           
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        HeaderPatient = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GoBackBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        totalAmount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dentalDescription = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        amountPaidLabel = new javax.swing.JLabel();
        amountPaid = new javax.swing.JTextField();
        addPatientInfo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbUL8 = new javax.swing.JCheckBox();
        cbUL7 = new javax.swing.JCheckBox();
        cbUL6 = new javax.swing.JCheckBox();
        cbUL5 = new javax.swing.JCheckBox();
        cbUL4 = new javax.swing.JCheckBox();
        cbUL3 = new javax.swing.JCheckBox();
        cbUL2 = new javax.swing.JCheckBox();
        cbUL1 = new javax.swing.JCheckBox();
        cbUR1 = new javax.swing.JCheckBox();
        cbUR2 = new javax.swing.JCheckBox();
        cbUR3 = new javax.swing.JCheckBox();
        cbUR4 = new javax.swing.JCheckBox();
        cbUR5 = new javax.swing.JCheckBox();
        cbUR6 = new javax.swing.JCheckBox();
        cbUR7 = new javax.swing.JCheckBox();
        cbUR8 = new javax.swing.JCheckBox();
        cbLR5 = new javax.swing.JCheckBox();
        cbULE = new javax.swing.JCheckBox();
        cbULD = new javax.swing.JCheckBox();
        cbULC = new javax.swing.JCheckBox();
        cbULB = new javax.swing.JCheckBox();
        cbULA = new javax.swing.JCheckBox();
        cbURA = new javax.swing.JCheckBox();
        cbURB = new javax.swing.JCheckBox();
        cbURC = new javax.swing.JCheckBox();
        cbURD = new javax.swing.JCheckBox();
        cbURE = new javax.swing.JCheckBox();
        cbLLE = new javax.swing.JCheckBox();
        cbLLD = new javax.swing.JCheckBox();
        cbLLC = new javax.swing.JCheckBox();
        cbLLB = new javax.swing.JCheckBox();
        cbLLA = new javax.swing.JCheckBox();
        cbLRA = new javax.swing.JCheckBox();
        cbLRB = new javax.swing.JCheckBox();
        cbLRC = new javax.swing.JCheckBox();
        cbLRD = new javax.swing.JCheckBox();
        cbLRE = new javax.swing.JCheckBox();
        cbLL8 = new javax.swing.JCheckBox();
        cbLL7 = new javax.swing.JCheckBox();
        cbLL6 = new javax.swing.JCheckBox();
        cbLL5 = new javax.swing.JCheckBox();
        cbLL4 = new javax.swing.JCheckBox();
        cbLL3 = new javax.swing.JCheckBox();
        cbLL2 = new javax.swing.JCheckBox();
        cbLL1 = new javax.swing.JCheckBox();
        cbLR1 = new javax.swing.JCheckBox();
        cbLR2 = new javax.swing.JCheckBox();
        cbLR3 = new javax.swing.JCheckBox();
        cbLR4 = new javax.swing.JCheckBox();
        cbLR6 = new javax.swing.JCheckBox();
        cbLR7 = new javax.swing.JCheckBox();
        cbLR8 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Patient Information | Diamse - Montero Dental Clinic");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderPatient.setBackground(new java.awt.Color(52, 152, 219));

        jLabel1.setBackground(new java.awt.Color(239, 249, 247));
        jLabel1.setFont(new java.awt.Font("Avenir", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 249, 247));
        jLabel1.setText("DIAMSE - MONTERO ");

        jLabel2.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel2.setText("D  E  N  T  A  L    C  L  I  N  I  C  ");

        GoBackBtn.setText("BACK");
        GoBackBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                GoBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderPatientLayout = new javax.swing.GroupLayout(HeaderPatient);
        HeaderPatient.setLayout(HeaderPatientLayout);
        HeaderPatientLayout.setHorizontalGroup(
            HeaderPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPatientLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(HeaderPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPatientLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(GoBackBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPatientLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(158, 158, 158))))
        );
        HeaderPatientLayout.setVerticalGroup(
            HeaderPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPatientLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HeaderPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(GoBackBtn))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(HeaderPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(41, 128, 185));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(totalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 219, -1));

        jLabel6.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Description:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        dentalDescription.setColumns(20);
        dentalDescription.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        dentalDescription.setLineWrap(true);
        dentalDescription.setRows(5);
        jScrollPane1.setViewportView(dentalDescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 260, 80));

        jLabel7.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Amount:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));

        amountPaidLabel.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        amountPaidLabel.setForeground(new java.awt.Color(255, 255, 255));
        amountPaidLabel.setText("Amount Paid:");
        jPanel1.add(amountPaidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));
        jPanel1.add(amountPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 219, -1));

        addPatientInfo.setText("Add Record");
        addPatientInfo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addPatientInfoActionPerformed(evt);
            }
        });
        jPanel1.add(addPatientInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        jPanel2.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teeth/tc1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        jLabel4.setBackground(new java.awt.Color(232, 76, 61));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teeth/tc2.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 660, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teeth/tc3.jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 670, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teeth/tc4.jpg"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 680, -1));

        cbUL8.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        cbUL7.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        cbUL6.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        cbUL5.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        cbUL4.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        cbUL3.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        cbUL2.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        cbUL1.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 50, -1, -1));

        cbUR1.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        cbUR2.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        cbUR3.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        cbUR4.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        cbUR5.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUR5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        cbUR6.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUR6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        cbUR7.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUR7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        cbUR8.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbUR8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, -1, -1));

        cbLR5.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLR5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 30, -1));

        cbULE.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbULE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        cbULD.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbULD, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        cbULC.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbULC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        cbULB.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbULB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        cbULA.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbULA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        cbURA.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbURA, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        cbURB.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbURB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        cbURC.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbURC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        cbURD.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbURD, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        cbURE.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbURE, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, -1));

        cbLLE.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        cbLLD.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        cbLLC.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        cbLLB.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        cbLLA.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        cbLRA.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        cbLRB.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        cbLRC.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        cbLRD.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        cbLRE.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));

        cbLL8.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        cbLL7.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        cbLL6.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        cbLL5.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        cbLL4.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        cbLL3.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        cbLL2.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        cbLL1.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 30, -1));

        cbLR1.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 30, -1));

        cbLR2.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 30, -1));

        cbLR3.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 30, -1));

        cbLR4.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 30, -1));

        cbLR6.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLR6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        cbLR7.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLR7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        cbLR8.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.add(cbLR8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addPatientInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientInfoActionPerformed
        // TODO add your handling code here:
        
         
        //java.sql.Date patDate = new java.sql.Date(DentalDate.getDate().getTime());
        //java.sql.Date sqlDate = new java.sql.Date(jDateChooser1.getDate().getTime());
        //java.sql.Date sqlDate = new java.sql.Date(Calendar.getInstance());
      //  java.sql.Timestamp sqlDate = new java.sql.Timestamp(new java.util.Date().getTime());
      
      
     
     
      ArrayList al = new ArrayList();
      if(cbLL1.isSelected()){
          al.add("LL1");
      } if(cbLL2.isSelected()){
          al.add("LL2");
      } if(cbLL3.isSelected()){
          al.add("LL3");
      } if(cbLL4.isSelected()){
          al.add("LL4");
      } if(cbLL5.isSelected()){
          al.add("LL5");
      } if(cbLL6.isSelected()){
          al.add("LL6");
      }  if(cbLL7.isSelected()){
          al.add("LL7");
      }  if(cbLL8.isSelected()){
          al.add("LL8");
      } if(cbLLA.isSelected()){
          al.add("LLA");
      } if(cbLLB.isSelected()){
          al.add("LLB");
      } if(cbLLC.isSelected()){
          al.add("LLC");
      } if(cbLLD.isSelected()){
          al.add("LLD");
      } if(cbLLE.isSelected()){
          al.add("LLE");
      } if(cbLR1.isSelected()){
          al.add("LR1");
      } if(cbLR2.isSelected()){
          al.add("LR2");
      } if(cbLR3.isSelected()){
          al.add("LR3");
      } if(cbLR4.isSelected()){
          al.add("LR4");
      } if(cbLR5.isSelected()){
          al.add("LR5");
      } if(cbLR6.isSelected()){
          al.add("LR6");
      } if(cbLR7.isSelected()){
          al.add("LR7");
      } if(cbLR8.isSelected()){
          al.add("LR8");
      } if(cbLRA.isSelected()){
          al.add("LRA");
      } if(cbLRB.isSelected()){
          al.add("LRB");
      } if(cbLRC.isSelected()){
          al.add("LRC");
      } if(cbLRD.isSelected()){
          al.add("LRD");
      } if(cbLRE.isSelected()){
          al.add("LRE");
      }
      if(cbUL1.isSelected()){
          al.add("UL1");
      } if(cbUL2.isSelected()){
          al.add("UL2");
      } if(cbUL3.isSelected()){
          al.add("UL3");
      } if(cbUL4.isSelected()){
          al.add("UL4");
      } if(cbUL5.isSelected()){
          al.add("UL5");
      } if(cbUL6.isSelected()){
          al.add("UL6");
      }  if(cbUL7.isSelected()){
          al.add("UL7");
      }  if(cbUL8.isSelected()){
          al.add("UL8");
      } if(cbULA.isSelected()){
          al.add("ULA");
      } if(cbULB.isSelected()){
          al.add("ULB");
      } if(cbULC.isSelected()){
          al.add("ULC");
      } if(cbULD.isSelected()){
          al.add("ULD");
      } if(cbULE.isSelected()){
          al.add("ULE");
      } if(cbUR1.isSelected()){
          al.add("UR1");
      } if(cbUR2.isSelected()){
          al.add("UR2");
      } if(cbUR3.isSelected()){
          al.add("UR3");
      } if(cbUR4.isSelected()){
          al.add("UR4");
      } if(cbUR5.isSelected()){
          al.add("UR5");
      } if(cbUR6.isSelected()){
          al.add("UR6");
      } if(cbUR7.isSelected()){
          al.add("UR7");
      } if(cbUR8.isSelected()){
          al.add("UR8");
      } if(cbURA.isSelected()){
          al.add("URA");
      } if(cbURB.isSelected()){
          al.add("URB");
      } if(cbURC.isSelected()){
          al.add("URC");
      } if(cbURD.isSelected()){
          al.add("URD");
      } if(cbURE.isSelected()){
          al.add("URE");
      }
          
          
          
      System.out.println(al);
      String tn = "";
      
      if(al.size()==0){
          tn="ALL";
      }
      else{
      for(int i=0; i < al.size(); i++){
          tn+=al.get(0).toString();
          if(i<al.size()-1){
              tn+=",";
          }
      }
      }
      
      java.util.Calendar cal = java.util.Calendar.getInstance();
      java.util.Date utilDate = cal.getTime();
      java.sql.Date sqlDate = new Date(utilDate.getTime());
        String ts = ZonedDateTime.now().format(DateTimeFormatter.ofLocalizedDateTime(FormatStyle.FULL, FormatStyle.MEDIUM));
        String event = "Added Dental Record for  Patient # "+patId+" Name: " +ln +", "+fn+".";
        Double bal = Double.parseDouble(totalAmount.getText()) - Double.parseDouble(amountPaid.getText());
        AddData(tn,sqlDate, dentalDescription.getText(), Double.parseDouble(totalAmount.getText()),Double.parseDouble(amountPaid.getText()), bal,ts,event);
        
      
        
        PatientRecords pr = new PatientRecords();
        new RowPopup(pr);
        new RowPopup2(pr);
        pr.setVisible(true);
        super.dispose();
        
        
        
    }//GEN-LAST:event_addPatientInfoActionPerformed

    private void GoBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackBtnActionPerformed
//        DentalRecords dr = new DentalRecords();
//        dr.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_GoBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDentalRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDentalRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDentalRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDentalRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDentalRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBackBtn;
    private javax.swing.JPanel HeaderPatient;
    private javax.swing.JButton addPatientInfo;
    private javax.swing.JTextField amountPaid;
    private javax.swing.JLabel amountPaidLabel;
    private javax.swing.JCheckBox cbLL1;
    private javax.swing.JCheckBox cbLL2;
    private javax.swing.JCheckBox cbLL3;
    private javax.swing.JCheckBox cbLL4;
    private javax.swing.JCheckBox cbLL5;
    private javax.swing.JCheckBox cbLL6;
    private javax.swing.JCheckBox cbLL7;
    private javax.swing.JCheckBox cbLL8;
    private javax.swing.JCheckBox cbLLA;
    private javax.swing.JCheckBox cbLLB;
    private javax.swing.JCheckBox cbLLC;
    private javax.swing.JCheckBox cbLLD;
    private javax.swing.JCheckBox cbLLE;
    private javax.swing.JCheckBox cbLR1;
    private javax.swing.JCheckBox cbLR2;
    private javax.swing.JCheckBox cbLR3;
    private javax.swing.JCheckBox cbLR4;
    private javax.swing.JCheckBox cbLR5;
    private javax.swing.JCheckBox cbLR6;
    private javax.swing.JCheckBox cbLR7;
    private javax.swing.JCheckBox cbLR8;
    private javax.swing.JCheckBox cbLRA;
    private javax.swing.JCheckBox cbLRB;
    private javax.swing.JCheckBox cbLRC;
    private javax.swing.JCheckBox cbLRD;
    private javax.swing.JCheckBox cbLRE;
    private javax.swing.JCheckBox cbUL1;
    private javax.swing.JCheckBox cbUL2;
    private javax.swing.JCheckBox cbUL3;
    private javax.swing.JCheckBox cbUL4;
    private javax.swing.JCheckBox cbUL5;
    private javax.swing.JCheckBox cbUL6;
    private javax.swing.JCheckBox cbUL7;
    private javax.swing.JCheckBox cbUL8;
    private javax.swing.JCheckBox cbULA;
    private javax.swing.JCheckBox cbULB;
    private javax.swing.JCheckBox cbULC;
    private javax.swing.JCheckBox cbULD;
    private javax.swing.JCheckBox cbULE;
    private javax.swing.JCheckBox cbUR1;
    private javax.swing.JCheckBox cbUR2;
    private javax.swing.JCheckBox cbUR3;
    private javax.swing.JCheckBox cbUR4;
    private javax.swing.JCheckBox cbUR5;
    private javax.swing.JCheckBox cbUR6;
    private javax.swing.JCheckBox cbUR7;
    private javax.swing.JCheckBox cbUR8;
    private javax.swing.JCheckBox cbURA;
    private javax.swing.JCheckBox cbURB;
    private javax.swing.JCheckBox cbURC;
    private javax.swing.JCheckBox cbURD;
    private javax.swing.JCheckBox cbURE;
    private javax.swing.JTextArea dentalDescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField totalAmount;
    // End of variables declaration//GEN-END:variables
}
